// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RESTAWSAccountKeyConfig REST a w s account key config
//
// swagger:model RESTAWSAccountKeyConfig
type RESTAWSAccountKeyConfig struct {

	// access key id
	AccessKeyID string `json:"access_key_id,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// region
	Region string `json:"region,omitempty"`

	// secret access key
	SecretAccessKey string `json:"secret_access_key,omitempty"`
}

// Validate validates this REST a w s account key config
func (m *RESTAWSAccountKeyConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RESTAWSAccountKeyConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTAWSAccountKeyConfig) UnmarshalBinary(b []byte) error {
	var res RESTAWSAccountKeyConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
