// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RESTGCRKey REST g c r key
//
// swagger:model RESTGCRKey
type RESTGCRKey struct {

	// json key
	JSONKey string `json:"json_key,omitempty"`
}

// Validate validates this REST g c r key
func (m *RESTGCRKey) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RESTGCRKey) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTGCRKey) UnmarshalBinary(b []byte) error {
	var res RESTGCRKey
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
