// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RESTJfrogXrayConfig REST jfrog xray config
//
// swagger:model RESTJfrogXrayConfig
type RESTJfrogXrayConfig struct {

	// enable
	Enable bool `json:"enable,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// url
	URL string `json:"url,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this REST jfrog xray config
func (m *RESTJfrogXrayConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RESTJfrogXrayConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTJfrogXrayConfig) UnmarshalBinary(b []byte) error {
	var res RESTJfrogXrayConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
