// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTLicenseKey REST license key
//
// swagger:model RESTLicenseKey
type RESTLicenseKey struct {

	// license key
	// Required: true
	LicenseKey *string `json:"license_key"`
}

// Validate validates this REST license key
func (m *RESTLicenseKey) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLicenseKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTLicenseKey) validateLicenseKey(formats strfmt.Registry) error {

	if err := validate.Required("license_key", "body", m.LicenseKey); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RESTLicenseKey) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTLicenseKey) UnmarshalBinary(b []byte) error {
	var res RESTLicenseKey
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
