// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTRegistryImageSummary REST registry image summary
//
// swagger:model RESTRegistryImageSummary
type RESTRegistryImageSummary struct {

	// author
	Author string `json:"author,omitempty"`

	// base os
	// Required: true
	BaseOs *string `json:"base_os"`

	// cvedb create time
	CvedbCreateTime string `json:"cvedb_create_time,omitempty"`

	// digest
	// Required: true
	Digest *string `json:"digest"`

	// domain
	// Required: true
	Domain *string `json:"domain"`

	// envs
	// Required: true
	Envs []string `json:"envs"`

	// high
	// Required: true
	High *int64 `json:"high"`

	// image id
	// Required: true
	ImageID *string `json:"image_id"`

	// labels
	// Required: true
	Labels *RESTRegistryImageSummaryLabels `json:"labels"`

	// layers
	// Required: true
	Layers []string `json:"layers"`

	// medium
	// Required: true
	Medium *int64 `json:"medium"`

	// repository
	// Required: true
	Repository *string `json:"repository"`

	// result
	// Required: true
	Result *string `json:"result"`

	// run as root
	// Required: true
	RunAsRoot *bool `json:"run_as_root"`

	// scanned at
	// Required: true
	ScannedAt *string `json:"scanned_at"`

	// scanned timestamp
	// Required: true
	ScannedTimestamp *int64 `json:"scanned_timestamp"`

	// scanner version
	// Required: true
	ScannerVersion *string `json:"scanner_version"`

	// status
	// Required: true
	Status *string `json:"status"`

	// tag
	// Required: true
	Tag *string `json:"tag"`
}

// Validate validates this REST registry image summary
func (m *RESTRegistryImageSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBaseOs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDigest(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDomain(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEnvs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHigh(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImageID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLabels(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLayers(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMedium(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRepository(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRunAsRoot(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScannedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScannedTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScannerVersion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTag(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTRegistryImageSummary) validateBaseOs(formats strfmt.Registry) error {

	if err := validate.Required("base_os", "body", m.BaseOs); err != nil {
		return err
	}

	return nil
}

func (m *RESTRegistryImageSummary) validateDigest(formats strfmt.Registry) error {

	if err := validate.Required("digest", "body", m.Digest); err != nil {
		return err
	}

	return nil
}

func (m *RESTRegistryImageSummary) validateDomain(formats strfmt.Registry) error {

	if err := validate.Required("domain", "body", m.Domain); err != nil {
		return err
	}

	return nil
}

func (m *RESTRegistryImageSummary) validateEnvs(formats strfmt.Registry) error {

	if err := validate.Required("envs", "body", m.Envs); err != nil {
		return err
	}

	return nil
}

func (m *RESTRegistryImageSummary) validateHigh(formats strfmt.Registry) error {

	if err := validate.Required("high", "body", m.High); err != nil {
		return err
	}

	return nil
}

func (m *RESTRegistryImageSummary) validateImageID(formats strfmt.Registry) error {

	if err := validate.Required("image_id", "body", m.ImageID); err != nil {
		return err
	}

	return nil
}

func (m *RESTRegistryImageSummary) validateLabels(formats strfmt.Registry) error {

	if err := validate.Required("labels", "body", m.Labels); err != nil {
		return err
	}

	if m.Labels != nil {
		if err := m.Labels.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("labels")
			}
			return err
		}
	}

	return nil
}

func (m *RESTRegistryImageSummary) validateLayers(formats strfmt.Registry) error {

	if err := validate.Required("layers", "body", m.Layers); err != nil {
		return err
	}

	return nil
}

func (m *RESTRegistryImageSummary) validateMedium(formats strfmt.Registry) error {

	if err := validate.Required("medium", "body", m.Medium); err != nil {
		return err
	}

	return nil
}

func (m *RESTRegistryImageSummary) validateRepository(formats strfmt.Registry) error {

	if err := validate.Required("repository", "body", m.Repository); err != nil {
		return err
	}

	return nil
}

func (m *RESTRegistryImageSummary) validateResult(formats strfmt.Registry) error {

	if err := validate.Required("result", "body", m.Result); err != nil {
		return err
	}

	return nil
}

func (m *RESTRegistryImageSummary) validateRunAsRoot(formats strfmt.Registry) error {

	if err := validate.Required("run_as_root", "body", m.RunAsRoot); err != nil {
		return err
	}

	return nil
}

func (m *RESTRegistryImageSummary) validateScannedAt(formats strfmt.Registry) error {

	if err := validate.Required("scanned_at", "body", m.ScannedAt); err != nil {
		return err
	}

	return nil
}

func (m *RESTRegistryImageSummary) validateScannedTimestamp(formats strfmt.Registry) error {

	if err := validate.Required("scanned_timestamp", "body", m.ScannedTimestamp); err != nil {
		return err
	}

	return nil
}

func (m *RESTRegistryImageSummary) validateScannerVersion(formats strfmt.Registry) error {

	if err := validate.Required("scanner_version", "body", m.ScannerVersion); err != nil {
		return err
	}

	return nil
}

func (m *RESTRegistryImageSummary) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

func (m *RESTRegistryImageSummary) validateTag(formats strfmt.Registry) error {

	if err := validate.Required("tag", "body", m.Tag); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RESTRegistryImageSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTRegistryImageSummary) UnmarshalBinary(b []byte) error {
	var res RESTRegistryImageSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// RESTRegistryImageSummaryLabels REST registry image summary labels
//
// swagger:model RESTRegistryImageSummaryLabels
type RESTRegistryImageSummaryLabels struct {

	// key
	Key []string `json:"key"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this REST registry image summary labels
func (m *RESTRegistryImageSummaryLabels) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RESTRegistryImageSummaryLabels) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTRegistryImageSummaryLabels) UnmarshalBinary(b []byte) error {
	var res RESTRegistryImageSummaryLabels
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
