// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTScanConfig REST scan config
//
// swagger:model RESTScanConfig
type RESTScanConfig struct {

	// auto scan
	// Required: true
	AutoScan *bool `json:"auto_scan"`
}

// Validate validates this REST scan config
func (m *RESTScanConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAutoScan(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTScanConfig) validateAutoScan(formats strfmt.Registry) error {

	if err := validate.Required("auto_scan", "body", m.AutoScan); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RESTScanConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTScanConfig) UnmarshalBinary(b []byte) error {
	var res RESTScanConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
