// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RESTToken REST token
//
// swagger:model RESTToken
type RESTToken struct {

	// default password
	// Required: true
	DefaultPassword *bool `json:"default_password"`

	// email
	// Required: true
	Email *string `json:"email"`

	// fullname
	// Required: true
	Fullname *string `json:"fullname"`

	// last login at
	// Required: true
	LastLoginAt *string `json:"last_login_at"`

	// last login timestamp
	// Required: true
	LastLoginTimestamp *int64 `json:"last_login_timestamp"`

	// locale
	// Required: true
	Locale *string `json:"locale"`

	// login count
	// Required: true
	LoginCount *uint32 `json:"login_count"`

	// modify password
	// Required: true
	ModifyPassword bool `json:"modify_password"`

	// password
	// Required: true
	Password *string `json:"password"`

	// role
	// Required: true
	Role *string `json:"role"`

	// role domains
	RoleDomains *RESTTokenRoleDomains `json:"role_domains,omitempty"`

	// server
	// Required: true
	Server *string `json:"server"`

	// timeout
	// Required: true
	Timeout *uint32 `json:"timeout"`

	// token
	// Required: true
	Token *string `json:"token"`

	// username
	// Required: true
	Username *string `json:"username"`
}

// Validate validates this REST token
func (m *RESTToken) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDefaultPassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFullname(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastLoginAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastLoginTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLocale(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLoginCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateModifyPassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoleDomains(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateServer(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimeout(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToken(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUsername(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RESTToken) validateDefaultPassword(formats strfmt.Registry) error {

	if err := validate.Required("default_password", "body", m.DefaultPassword); err != nil {
		return err
	}

	return nil
}

func (m *RESTToken) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	return nil
}

func (m *RESTToken) validateFullname(formats strfmt.Registry) error {

	if err := validate.Required("fullname", "body", m.Fullname); err != nil {
		return err
	}

	return nil
}

func (m *RESTToken) validateLastLoginAt(formats strfmt.Registry) error {

	if err := validate.Required("last_login_at", "body", m.LastLoginAt); err != nil {
		return err
	}

	return nil
}

func (m *RESTToken) validateLastLoginTimestamp(formats strfmt.Registry) error {

	if err := validate.Required("last_login_timestamp", "body", m.LastLoginTimestamp); err != nil {
		return err
	}

	return nil
}

func (m *RESTToken) validateLocale(formats strfmt.Registry) error {

	if err := validate.Required("locale", "body", m.Locale); err != nil {
		return err
	}

	return nil
}

func (m *RESTToken) validateLoginCount(formats strfmt.Registry) error {

	if err := validate.Required("login_count", "body", m.LoginCount); err != nil {
		return err
	}

	return nil
}

func (m *RESTToken) validateModifyPassword(formats strfmt.Registry) error {

	if err := validate.Required("modify_password", "body", bool(m.ModifyPassword)); err != nil {
		return err
	}

	return nil
}

func (m *RESTToken) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	return nil
}

func (m *RESTToken) validateRole(formats strfmt.Registry) error {

	if err := validate.Required("role", "body", m.Role); err != nil {
		return err
	}

	return nil
}

func (m *RESTToken) validateRoleDomains(formats strfmt.Registry) error {

	if swag.IsZero(m.RoleDomains) { // not required
		return nil
	}

	if m.RoleDomains != nil {
		if err := m.RoleDomains.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("role_domains")
			}
			return err
		}
	}

	return nil
}

func (m *RESTToken) validateServer(formats strfmt.Registry) error {

	if err := validate.Required("server", "body", m.Server); err != nil {
		return err
	}

	return nil
}

func (m *RESTToken) validateTimeout(formats strfmt.Registry) error {

	if err := validate.Required("timeout", "body", m.Timeout); err != nil {
		return err
	}

	return nil
}

func (m *RESTToken) validateToken(formats strfmt.Registry) error {

	if err := validate.Required("token", "body", m.Token); err != nil {
		return err
	}

	return nil
}

func (m *RESTToken) validateUsername(formats strfmt.Registry) error {

	if err := validate.Required("username", "body", m.Username); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RESTToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTToken) UnmarshalBinary(b []byte) error {
	var res RESTToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// RESTTokenRoleDomains REST token role domains
//
// swagger:model RESTTokenRoleDomains
type RESTTokenRoleDomains struct {

	// domains
	Domains []string `json:"domains"`

	// role
	Role string `json:"role,omitempty"`
}

// Validate validates this REST token role domains
func (m *RESTTokenRoleDomains) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RESTTokenRoleDomains) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTTokenRoleDomains) UnmarshalBinary(b []byte) error {
	var res RESTTokenRoleDomains
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
