// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RESTUnquarReq REST unquar req
//
// swagger:model RESTUnquarReq
type RESTUnquarReq struct {

	// group
	Group string `json:"group,omitempty"`

	// response rule
	ResponseRule uint32 `json:"response_rule,omitempty"`
}

// Validate validates this REST unquar req
func (m *RESTUnquarReq) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RESTUnquarReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RESTUnquarReq) UnmarshalBinary(b []byte) error {
	var res RESTUnquarReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
