// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteScanRegistryNameScanReader is a Reader for the DeleteScanRegistryNameScan structure.
type DeleteScanRegistryNameScanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteScanRegistryNameScanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteScanRegistryNameScanOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteScanRegistryNameScanOK creates a DeleteScanRegistryNameScanOK with default headers values
func NewDeleteScanRegistryNameScanOK() *DeleteScanRegistryNameScanOK {
	return &DeleteScanRegistryNameScanOK{}
}

/*DeleteScanRegistryNameScanOK handles this case with default header values.

Success
*/
type DeleteScanRegistryNameScanOK struct {
}

func (o *DeleteScanRegistryNameScanOK) Error() string {
	return fmt.Sprintf("[DELETE /scan/registry/{name}/scan][%d] deleteScanRegistryNameScanOK ", 200)
}

func (o *DeleteScanRegistryNameScanOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
