// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteScanRegistryNameScanParams creates a new DeleteScanRegistryNameScanParams object
// with the default values initialized.
func NewDeleteScanRegistryNameScanParams() *DeleteScanRegistryNameScanParams {
	var ()
	return &DeleteScanRegistryNameScanParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteScanRegistryNameScanParamsWithTimeout creates a new DeleteScanRegistryNameScanParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteScanRegistryNameScanParamsWithTimeout(timeout time.Duration) *DeleteScanRegistryNameScanParams {
	var ()
	return &DeleteScanRegistryNameScanParams{

		timeout: timeout,
	}
}

// NewDeleteScanRegistryNameScanParamsWithContext creates a new DeleteScanRegistryNameScanParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteScanRegistryNameScanParamsWithContext(ctx context.Context) *DeleteScanRegistryNameScanParams {
	var ()
	return &DeleteScanRegistryNameScanParams{

		Context: ctx,
	}
}

// NewDeleteScanRegistryNameScanParamsWithHTTPClient creates a new DeleteScanRegistryNameScanParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteScanRegistryNameScanParamsWithHTTPClient(client *http.Client) *DeleteScanRegistryNameScanParams {
	var ()
	return &DeleteScanRegistryNameScanParams{
		HTTPClient: client,
	}
}

/*DeleteScanRegistryNameScanParams contains all the parameters to send to the API endpoint
for the delete scan registry name scan operation typically these are written to a http.Request
*/
type DeleteScanRegistryNameScanParams struct {

	/*XAuthToken*/
	XAuthToken string
	/*Name
	  Name of the registry

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete scan registry name scan params
func (o *DeleteScanRegistryNameScanParams) WithTimeout(timeout time.Duration) *DeleteScanRegistryNameScanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete scan registry name scan params
func (o *DeleteScanRegistryNameScanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete scan registry name scan params
func (o *DeleteScanRegistryNameScanParams) WithContext(ctx context.Context) *DeleteScanRegistryNameScanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete scan registry name scan params
func (o *DeleteScanRegistryNameScanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete scan registry name scan params
func (o *DeleteScanRegistryNameScanParams) WithHTTPClient(client *http.Client) *DeleteScanRegistryNameScanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete scan registry name scan params
func (o *DeleteScanRegistryNameScanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the delete scan registry name scan params
func (o *DeleteScanRegistryNameScanParams) WithXAuthToken(xAuthToken string) *DeleteScanRegistryNameScanParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the delete scan registry name scan params
func (o *DeleteScanRegistryNameScanParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithName adds the name to the delete scan registry name scan params
func (o *DeleteScanRegistryNameScanParams) WithName(name string) *DeleteScanRegistryNameScanParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete scan registry name scan params
func (o *DeleteScanRegistryNameScanParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteScanRegistryNameScanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
