// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/neuvector/models"
)

// GetScanRegistryNameLayersIDReader is a Reader for the GetScanRegistryNameLayersID structure.
type GetScanRegistryNameLayersIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScanRegistryNameLayersIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScanRegistryNameLayersIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetScanRegistryNameLayersIDOK creates a GetScanRegistryNameLayersIDOK with default headers values
func NewGetScanRegistryNameLayersIDOK() *GetScanRegistryNameLayersIDOK {
	return &GetScanRegistryNameLayersIDOK{}
}

/*GetScanRegistryNameLayersIDOK handles this case with default header values.

Success
*/
type GetScanRegistryNameLayersIDOK struct {
	Payload *models.RESTScanLayersReportData
}

func (o *GetScanRegistryNameLayersIDOK) Error() string {
	return fmt.Sprintf("[GET /scan/registry/{name}/layers/{id}][%d] getScanRegistryNameLayersIdOK  %+v", 200, o.Payload)
}

func (o *GetScanRegistryNameLayersIDOK) GetPayload() *models.RESTScanLayersReportData {
	return o.Payload
}

func (o *GetScanRegistryNameLayersIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTScanLayersReportData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
