// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetScanRegistryNameImagesParams creates a new GetScanRegistryNameImagesParams object
// with the default values initialized.
func NewGetScanRegistryNameImagesParams() *GetScanRegistryNameImagesParams {
	var ()
	return &GetScanRegistryNameImagesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetScanRegistryNameImagesParamsWithTimeout creates a new GetScanRegistryNameImagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetScanRegistryNameImagesParamsWithTimeout(timeout time.Duration) *GetScanRegistryNameImagesParams {
	var ()
	return &GetScanRegistryNameImagesParams{

		timeout: timeout,
	}
}

// NewGetScanRegistryNameImagesParamsWithContext creates a new GetScanRegistryNameImagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetScanRegistryNameImagesParamsWithContext(ctx context.Context) *GetScanRegistryNameImagesParams {
	var ()
	return &GetScanRegistryNameImagesParams{

		Context: ctx,
	}
}

// NewGetScanRegistryNameImagesParamsWithHTTPClient creates a new GetScanRegistryNameImagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetScanRegistryNameImagesParamsWithHTTPClient(client *http.Client) *GetScanRegistryNameImagesParams {
	var ()
	return &GetScanRegistryNameImagesParams{
		HTTPClient: client,
	}
}

/*GetScanRegistryNameImagesParams contains all the parameters to send to the API endpoint
for the get scan registry name images operation typically these are written to a http.Request
*/
type GetScanRegistryNameImagesParams struct {

	/*XAuthToken*/
	XAuthToken string
	/*Name
	  Name of the registry

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get scan registry name images params
func (o *GetScanRegistryNameImagesParams) WithTimeout(timeout time.Duration) *GetScanRegistryNameImagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get scan registry name images params
func (o *GetScanRegistryNameImagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get scan registry name images params
func (o *GetScanRegistryNameImagesParams) WithContext(ctx context.Context) *GetScanRegistryNameImagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get scan registry name images params
func (o *GetScanRegistryNameImagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get scan registry name images params
func (o *GetScanRegistryNameImagesParams) WithHTTPClient(client *http.Client) *GetScanRegistryNameImagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get scan registry name images params
func (o *GetScanRegistryNameImagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get scan registry name images params
func (o *GetScanRegistryNameImagesParams) WithXAuthToken(xAuthToken string) *GetScanRegistryNameImagesParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get scan registry name images params
func (o *GetScanRegistryNameImagesParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithName adds the name to the get scan registry name images params
func (o *GetScanRegistryNameImagesParams) WithName(name string) *GetScanRegistryNameImagesParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get scan registry name images params
func (o *GetScanRegistryNameImagesParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetScanRegistryNameImagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
