// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/neuvector/models"
)

// GetScanRegistryNameImagesReader is a Reader for the GetScanRegistryNameImages structure.
type GetScanRegistryNameImagesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScanRegistryNameImagesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScanRegistryNameImagesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetScanRegistryNameImagesOK creates a GetScanRegistryNameImagesOK with default headers values
func NewGetScanRegistryNameImagesOK() *GetScanRegistryNameImagesOK {
	return &GetScanRegistryNameImagesOK{}
}

/*GetScanRegistryNameImagesOK handles this case with default header values.

Success
*/
type GetScanRegistryNameImagesOK struct {
	Payload *models.RESTRegistryImageSummaryData
}

func (o *GetScanRegistryNameImagesOK) Error() string {
	return fmt.Sprintf("[GET /scan/registry/{name}/images][%d] getScanRegistryNameImagesOK  %+v", 200, o.Payload)
}

func (o *GetScanRegistryNameImagesOK) GetPayload() *models.RESTRegistryImageSummaryData {
	return o.Payload
}

func (o *GetScanRegistryNameImagesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTRegistryImageSummaryData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
