// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/neuvector/models"
)

// GetScanWorkloadIDReader is a Reader for the GetScanWorkloadID structure.
type GetScanWorkloadIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScanWorkloadIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScanWorkloadIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetScanWorkloadIDOK creates a GetScanWorkloadIDOK with default headers values
func NewGetScanWorkloadIDOK() *GetScanWorkloadIDOK {
	return &GetScanWorkloadIDOK{}
}

/*GetScanWorkloadIDOK handles this case with default header values.

Success
*/
type GetScanWorkloadIDOK struct {
	Payload *models.RESTScanReportData
}

func (o *GetScanWorkloadIDOK) Error() string {
	return fmt.Sprintf("[GET /scan/workload/{id}][%d] getScanWorkloadIdOK  %+v", 200, o.Payload)
}

func (o *GetScanWorkloadIDOK) GetPayload() *models.RESTScanReportData {
	return o.Payload
}

func (o *GetScanWorkloadIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTScanReportData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
