// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/neuvector/models"
)

// GetScanImageReader is a Reader for the GetScanImage structure.
type GetScanImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScanImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScanImageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetScanImageOK creates a GetScanImageOK with default headers values
func NewGetScanImageOK() *GetScanImageOK {
	return &GetScanImageOK{}
}

/*GetScanImageOK handles this case with default header values.

Success
*/
type GetScanImageOK struct {
	Payload *models.RESTScanImageSummaryData
}

func (o *GetScanImageOK) Error() string {
	return fmt.Sprintf("[GET /scan/image][%d] getScanImageOK  %+v", 200, o.Payload)
}

func (o *GetScanImageOK) GetPayload() *models.RESTScanImageSummaryData {
	return o.Payload
}

func (o *GetScanImageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTScanImageSummaryData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
