// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetScanImageIDParams creates a new GetScanImageIDParams object
// with the default values initialized.
func NewGetScanImageIDParams() *GetScanImageIDParams {
	var ()
	return &GetScanImageIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetScanImageIDParamsWithTimeout creates a new GetScanImageIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetScanImageIDParamsWithTimeout(timeout time.Duration) *GetScanImageIDParams {
	var ()
	return &GetScanImageIDParams{

		timeout: timeout,
	}
}

// NewGetScanImageIDParamsWithContext creates a new GetScanImageIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetScanImageIDParamsWithContext(ctx context.Context) *GetScanImageIDParams {
	var ()
	return &GetScanImageIDParams{

		Context: ctx,
	}
}

// NewGetScanImageIDParamsWithHTTPClient creates a new GetScanImageIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetScanImageIDParamsWithHTTPClient(client *http.Client) *GetScanImageIDParams {
	var ()
	return &GetScanImageIDParams{
		HTTPClient: client,
	}
}

/*GetScanImageIDParams contains all the parameters to send to the API endpoint
for the get scan image ID operation typically these are written to a http.Request
*/
type GetScanImageIDParams struct {

	/*XAuthToken*/
	XAuthToken string
	/*ID
	  Image id

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get scan image ID params
func (o *GetScanImageIDParams) WithTimeout(timeout time.Duration) *GetScanImageIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get scan image ID params
func (o *GetScanImageIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get scan image ID params
func (o *GetScanImageIDParams) WithContext(ctx context.Context) *GetScanImageIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get scan image ID params
func (o *GetScanImageIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get scan image ID params
func (o *GetScanImageIDParams) WithHTTPClient(client *http.Client) *GetScanImageIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get scan image ID params
func (o *GetScanImageIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get scan image ID params
func (o *GetScanImageIDParams) WithXAuthToken(xAuthToken string) *GetScanImageIDParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get scan image ID params
func (o *GetScanImageIDParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithID adds the id to the get scan image ID params
func (o *GetScanImageIDParams) WithID(id string) *GetScanImageIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get scan image ID params
func (o *GetScanImageIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetScanImageIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
