// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetScanRegistryParams creates a new GetScanRegistryParams object
// with the default values initialized.
func NewGetScanRegistryParams() *GetScanRegistryParams {
	var ()
	return &GetScanRegistryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetScanRegistryParamsWithTimeout creates a new GetScanRegistryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetScanRegistryParamsWithTimeout(timeout time.Duration) *GetScanRegistryParams {
	var ()
	return &GetScanRegistryParams{

		timeout: timeout,
	}
}

// NewGetScanRegistryParamsWithContext creates a new GetScanRegistryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetScanRegistryParamsWithContext(ctx context.Context) *GetScanRegistryParams {
	var ()
	return &GetScanRegistryParams{

		Context: ctx,
	}
}

// NewGetScanRegistryParamsWithHTTPClient creates a new GetScanRegistryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetScanRegistryParamsWithHTTPClient(client *http.Client) *GetScanRegistryParams {
	var ()
	return &GetScanRegistryParams{
		HTTPClient: client,
	}
}

/*GetScanRegistryParams contains all the parameters to send to the API endpoint
for the get scan registry operation typically these are written to a http.Request
*/
type GetScanRegistryParams struct {

	/*XAuthToken*/
	XAuthToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get scan registry params
func (o *GetScanRegistryParams) WithTimeout(timeout time.Duration) *GetScanRegistryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get scan registry params
func (o *GetScanRegistryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get scan registry params
func (o *GetScanRegistryParams) WithContext(ctx context.Context) *GetScanRegistryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get scan registry params
func (o *GetScanRegistryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get scan registry params
func (o *GetScanRegistryParams) WithHTTPClient(client *http.Client) *GetScanRegistryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get scan registry params
func (o *GetScanRegistryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get scan registry params
func (o *GetScanRegistryParams) WithXAuthToken(xAuthToken string) *GetScanRegistryParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get scan registry params
func (o *GetScanRegistryParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WriteToRequest writes these params to a swagger request
func (o *GetScanRegistryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
