// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetScanHostIDParams creates a new GetScanHostIDParams object
// with the default values initialized.
func NewGetScanHostIDParams() *GetScanHostIDParams {
	var ()
	return &GetScanHostIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetScanHostIDParamsWithTimeout creates a new GetScanHostIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetScanHostIDParamsWithTimeout(timeout time.Duration) *GetScanHostIDParams {
	var ()
	return &GetScanHostIDParams{

		timeout: timeout,
	}
}

// NewGetScanHostIDParamsWithContext creates a new GetScanHostIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetScanHostIDParamsWithContext(ctx context.Context) *GetScanHostIDParams {
	var ()
	return &GetScanHostIDParams{

		Context: ctx,
	}
}

// NewGetScanHostIDParamsWithHTTPClient creates a new GetScanHostIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetScanHostIDParamsWithHTTPClient(client *http.Client) *GetScanHostIDParams {
	var ()
	return &GetScanHostIDParams{
		HTTPClient: client,
	}
}

/*GetScanHostIDParams contains all the parameters to send to the API endpoint
for the get scan host ID operation typically these are written to a http.Request
*/
type GetScanHostIDParams struct {

	/*XAuthToken*/
	XAuthToken string
	/*ID
	  Host ID

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get scan host ID params
func (o *GetScanHostIDParams) WithTimeout(timeout time.Duration) *GetScanHostIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get scan host ID params
func (o *GetScanHostIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get scan host ID params
func (o *GetScanHostIDParams) WithContext(ctx context.Context) *GetScanHostIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get scan host ID params
func (o *GetScanHostIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get scan host ID params
func (o *GetScanHostIDParams) WithHTTPClient(client *http.Client) *GetScanHostIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get scan host ID params
func (o *GetScanHostIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get scan host ID params
func (o *GetScanHostIDParams) WithXAuthToken(xAuthToken string) *GetScanHostIDParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get scan host ID params
func (o *GetScanHostIDParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithID adds the id to the get scan host ID params
func (o *GetScanHostIDParams) WithID(id string) *GetScanHostIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get scan host ID params
func (o *GetScanHostIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetScanHostIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
