// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetScanStatusParams creates a new GetScanStatusParams object
// with the default values initialized.
func NewGetScanStatusParams() *GetScanStatusParams {
	var ()
	return &GetScanStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetScanStatusParamsWithTimeout creates a new GetScanStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetScanStatusParamsWithTimeout(timeout time.Duration) *GetScanStatusParams {
	var ()
	return &GetScanStatusParams{

		timeout: timeout,
	}
}

// NewGetScanStatusParamsWithContext creates a new GetScanStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetScanStatusParamsWithContext(ctx context.Context) *GetScanStatusParams {
	var ()
	return &GetScanStatusParams{

		Context: ctx,
	}
}

// NewGetScanStatusParamsWithHTTPClient creates a new GetScanStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetScanStatusParamsWithHTTPClient(client *http.Client) *GetScanStatusParams {
	var ()
	return &GetScanStatusParams{
		HTTPClient: client,
	}
}

/*GetScanStatusParams contains all the parameters to send to the API endpoint
for the get scan status operation typically these are written to a http.Request
*/
type GetScanStatusParams struct {

	/*XAuthToken*/
	XAuthToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get scan status params
func (o *GetScanStatusParams) WithTimeout(timeout time.Duration) *GetScanStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get scan status params
func (o *GetScanStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get scan status params
func (o *GetScanStatusParams) WithContext(ctx context.Context) *GetScanStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get scan status params
func (o *GetScanStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get scan status params
func (o *GetScanStatusParams) WithHTTPClient(client *http.Client) *GetScanStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get scan status params
func (o *GetScanStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get scan status params
func (o *GetScanStatusParams) WithXAuthToken(xAuthToken string) *GetScanStatusParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get scan status params
func (o *GetScanStatusParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WriteToRequest writes these params to a swagger request
func (o *GetScanStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
