// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/neuvector/models"
)

// GetScanHostIDReader is a Reader for the GetScanHostID structure.
type GetScanHostIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScanHostIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScanHostIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetScanHostIDOK creates a GetScanHostIDOK with default headers values
func NewGetScanHostIDOK() *GetScanHostIDOK {
	return &GetScanHostIDOK{}
}

/*GetScanHostIDOK handles this case with default header values.

Success
*/
type GetScanHostIDOK struct {
	Payload *models.RESTScanReportData
}

func (o *GetScanHostIDOK) Error() string {
	return fmt.Sprintf("[GET /scan/host/{id}][%d] getScanHostIdOK  %+v", 200, o.Payload)
}

func (o *GetScanHostIDOK) GetPayload() *models.RESTScanReportData {
	return o.Payload
}

func (o *GetScanHostIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTScanReportData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
