// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/neuvector/models"
)

// GetScanRegistryNameReader is a Reader for the GetScanRegistryName structure.
type GetScanRegistryNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScanRegistryNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScanRegistryNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetScanRegistryNameOK creates a GetScanRegistryNameOK with default headers values
func NewGetScanRegistryNameOK() *GetScanRegistryNameOK {
	return &GetScanRegistryNameOK{}
}

/*GetScanRegistryNameOK handles this case with default header values.

Success
*/
type GetScanRegistryNameOK struct {
	Payload *models.RESTRegistrySummaryData
}

func (o *GetScanRegistryNameOK) Error() string {
	return fmt.Sprintf("[GET /scan/registry/{name}][%d] getScanRegistryNameOK  %+v", 200, o.Payload)
}

func (o *GetScanRegistryNameOK) GetPayload() *models.RESTRegistrySummaryData {
	return o.Payload
}

func (o *GetScanRegistryNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTRegistrySummaryData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
