// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetScanPlatformParams creates a new GetScanPlatformParams object
// with the default values initialized.
func NewGetScanPlatformParams() *GetScanPlatformParams {
	var ()
	return &GetScanPlatformParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetScanPlatformParamsWithTimeout creates a new GetScanPlatformParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetScanPlatformParamsWithTimeout(timeout time.Duration) *GetScanPlatformParams {
	var ()
	return &GetScanPlatformParams{

		timeout: timeout,
	}
}

// NewGetScanPlatformParamsWithContext creates a new GetScanPlatformParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetScanPlatformParamsWithContext(ctx context.Context) *GetScanPlatformParams {
	var ()
	return &GetScanPlatformParams{

		Context: ctx,
	}
}

// NewGetScanPlatformParamsWithHTTPClient creates a new GetScanPlatformParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetScanPlatformParamsWithHTTPClient(client *http.Client) *GetScanPlatformParams {
	var ()
	return &GetScanPlatformParams{
		HTTPClient: client,
	}
}

/*GetScanPlatformParams contains all the parameters to send to the API endpoint
for the get scan platform operation typically these are written to a http.Request
*/
type GetScanPlatformParams struct {

	/*XAuthToken*/
	XAuthToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get scan platform params
func (o *GetScanPlatformParams) WithTimeout(timeout time.Duration) *GetScanPlatformParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get scan platform params
func (o *GetScanPlatformParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get scan platform params
func (o *GetScanPlatformParams) WithContext(ctx context.Context) *GetScanPlatformParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get scan platform params
func (o *GetScanPlatformParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get scan platform params
func (o *GetScanPlatformParams) WithHTTPClient(client *http.Client) *GetScanPlatformParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get scan platform params
func (o *GetScanPlatformParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get scan platform params
func (o *GetScanPlatformParams) WithXAuthToken(xAuthToken string) *GetScanPlatformParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get scan platform params
func (o *GetScanPlatformParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WriteToRequest writes these params to a swagger request
func (o *GetScanPlatformParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
