// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/neuvector/models"
)

// GetScanStatusReader is a Reader for the GetScanStatus structure.
type GetScanStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScanStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScanStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetScanStatusOK creates a GetScanStatusOK with default headers values
func NewGetScanStatusOK() *GetScanStatusOK {
	return &GetScanStatusOK{}
}

/*GetScanStatusOK handles this case with default header values.

Success
*/
type GetScanStatusOK struct {
	Payload *models.RESTScanStatusData
}

func (o *GetScanStatusOK) Error() string {
	return fmt.Sprintf("[GET /scan/status][%d] getScanStatusOK  %+v", 200, o.Payload)
}

func (o *GetScanStatusOK) GetPayload() *models.RESTScanStatusData {
	return o.Payload
}

func (o *GetScanStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTScanStatusData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
