// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PatchScanConfigReader is a Reader for the PatchScanConfig structure.
type PatchScanConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchScanConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchScanConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchScanConfigOK creates a PatchScanConfigOK with default headers values
func NewPatchScanConfigOK() *PatchScanConfigOK {
	return &PatchScanConfigOK{}
}

/*PatchScanConfigOK handles this case with default header values.

Success
*/
type PatchScanConfigOK struct {
}

func (o *PatchScanConfigOK) Error() string {
	return fmt.Sprintf("[PATCH /scan/config][%d] patchScanConfigOK ", 200)
}

func (o *PatchScanConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
