// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PatchScanRegistryNameReader is a Reader for the PatchScanRegistryName structure.
type PatchScanRegistryNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchScanRegistryNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchScanRegistryNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchScanRegistryNameOK creates a PatchScanRegistryNameOK with default headers values
func NewPatchScanRegistryNameOK() *PatchScanRegistryNameOK {
	return &PatchScanRegistryNameOK{}
}

/*PatchScanRegistryNameOK handles this case with default header values.

Success
*/
type PatchScanRegistryNameOK struct {
}

func (o *PatchScanRegistryNameOK) Error() string {
	return fmt.Sprintf("[PATCH /scan/registry/{name}][%d] patchScanRegistryNameOK ", 200)
}

func (o *PatchScanRegistryNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
