// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/neuvector/models"
)

// NewPatchScanRegistryNameParams creates a new PatchScanRegistryNameParams object
// with the default values initialized.
func NewPatchScanRegistryNameParams() *PatchScanRegistryNameParams {
	var ()
	return &PatchScanRegistryNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchScanRegistryNameParamsWithTimeout creates a new PatchScanRegistryNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchScanRegistryNameParamsWithTimeout(timeout time.Duration) *PatchScanRegistryNameParams {
	var ()
	return &PatchScanRegistryNameParams{

		timeout: timeout,
	}
}

// NewPatchScanRegistryNameParamsWithContext creates a new PatchScanRegistryNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchScanRegistryNameParamsWithContext(ctx context.Context) *PatchScanRegistryNameParams {
	var ()
	return &PatchScanRegistryNameParams{

		Context: ctx,
	}
}

// NewPatchScanRegistryNameParamsWithHTTPClient creates a new PatchScanRegistryNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchScanRegistryNameParamsWithHTTPClient(client *http.Client) *PatchScanRegistryNameParams {
	var ()
	return &PatchScanRegistryNameParams{
		HTTPClient: client,
	}
}

/*PatchScanRegistryNameParams contains all the parameters to send to the API endpoint
for the patch scan registry name operation typically these are written to a http.Request
*/
type PatchScanRegistryNameParams struct {

	/*XAuthToken*/
	XAuthToken string
	/*Body
	  Registry data

	*/
	Body *models.RESTRegistryConfigData
	/*Name
	  Name of the registry

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch scan registry name params
func (o *PatchScanRegistryNameParams) WithTimeout(timeout time.Duration) *PatchScanRegistryNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch scan registry name params
func (o *PatchScanRegistryNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch scan registry name params
func (o *PatchScanRegistryNameParams) WithContext(ctx context.Context) *PatchScanRegistryNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch scan registry name params
func (o *PatchScanRegistryNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch scan registry name params
func (o *PatchScanRegistryNameParams) WithHTTPClient(client *http.Client) *PatchScanRegistryNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch scan registry name params
func (o *PatchScanRegistryNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the patch scan registry name params
func (o *PatchScanRegistryNameParams) WithXAuthToken(xAuthToken string) *PatchScanRegistryNameParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the patch scan registry name params
func (o *PatchScanRegistryNameParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithBody adds the body to the patch scan registry name params
func (o *PatchScanRegistryNameParams) WithBody(body *models.RESTRegistryConfigData) *PatchScanRegistryNameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch scan registry name params
func (o *PatchScanRegistryNameParams) SetBody(body *models.RESTRegistryConfigData) {
	o.Body = body
}

// WithName adds the name to the patch scan registry name params
func (o *PatchScanRegistryNameParams) WithName(name string) *PatchScanRegistryNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the patch scan registry name params
func (o *PatchScanRegistryNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PatchScanRegistryNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
