// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/neuvector/models"
)

// PostScanPackageReader is a Reader for the PostScanPackage structure.
type PostScanPackageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostScanPackageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostScanPackageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostScanPackageOK creates a PostScanPackageOK with default headers values
func NewPostScanPackageOK() *PostScanPackageOK {
	return &PostScanPackageOK{}
}

/*PostScanPackageOK handles this case with default header values.

Success
*/
type PostScanPackageOK struct {
	Payload *models.RESTScanPkgReportData
}

func (o *PostScanPackageOK) Error() string {
	return fmt.Sprintf("[POST /scan/package][%d] postScanPackageOK  %+v", 200, o.Payload)
}

func (o *PostScanPackageOK) GetPayload() *models.RESTScanPkgReportData {
	return o.Payload
}

func (o *PostScanPackageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTScanPkgReportData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
