// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostScanRegistryReader is a Reader for the PostScanRegistry structure.
type PostScanRegistryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostScanRegistryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostScanRegistryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostScanRegistryOK creates a PostScanRegistryOK with default headers values
func NewPostScanRegistryOK() *PostScanRegistryOK {
	return &PostScanRegistryOK{}
}

/*PostScanRegistryOK handles this case with default header values.

Success
*/
type PostScanRegistryOK struct {
}

func (o *PostScanRegistryOK) Error() string {
	return fmt.Sprintf("[POST /scan/registry][%d] postScanRegistryOK ", 200)
}

func (o *PostScanRegistryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
