// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostScanPlatformPlatformParams creates a new PostScanPlatformPlatformParams object
// with the default values initialized.
func NewPostScanPlatformPlatformParams() *PostScanPlatformPlatformParams {
	var ()
	return &PostScanPlatformPlatformParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostScanPlatformPlatformParamsWithTimeout creates a new PostScanPlatformPlatformParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostScanPlatformPlatformParamsWithTimeout(timeout time.Duration) *PostScanPlatformPlatformParams {
	var ()
	return &PostScanPlatformPlatformParams{

		timeout: timeout,
	}
}

// NewPostScanPlatformPlatformParamsWithContext creates a new PostScanPlatformPlatformParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostScanPlatformPlatformParamsWithContext(ctx context.Context) *PostScanPlatformPlatformParams {
	var ()
	return &PostScanPlatformPlatformParams{

		Context: ctx,
	}
}

// NewPostScanPlatformPlatformParamsWithHTTPClient creates a new PostScanPlatformPlatformParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostScanPlatformPlatformParamsWithHTTPClient(client *http.Client) *PostScanPlatformPlatformParams {
	var ()
	return &PostScanPlatformPlatformParams{
		HTTPClient: client,
	}
}

/*PostScanPlatformPlatformParams contains all the parameters to send to the API endpoint
for the post scan platform platform operation typically these are written to a http.Request
*/
type PostScanPlatformPlatformParams struct {

	/*XAuthToken*/
	XAuthToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post scan platform platform params
func (o *PostScanPlatformPlatformParams) WithTimeout(timeout time.Duration) *PostScanPlatformPlatformParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post scan platform platform params
func (o *PostScanPlatformPlatformParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post scan platform platform params
func (o *PostScanPlatformPlatformParams) WithContext(ctx context.Context) *PostScanPlatformPlatformParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post scan platform platform params
func (o *PostScanPlatformPlatformParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post scan platform platform params
func (o *PostScanPlatformPlatformParams) WithHTTPClient(client *http.Client) *PostScanPlatformPlatformParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post scan platform platform params
func (o *PostScanPlatformPlatformParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the post scan platform platform params
func (o *PostScanPlatformPlatformParams) WithXAuthToken(xAuthToken string) *PostScanPlatformPlatformParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the post scan platform platform params
func (o *PostScanPlatformPlatformParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WriteToRequest writes these params to a swagger request
func (o *PostScanPlatformPlatformParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
