// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostScanRegistryNameScanParams creates a new PostScanRegistryNameScanParams object
// with the default values initialized.
func NewPostScanRegistryNameScanParams() *PostScanRegistryNameScanParams {
	var ()
	return &PostScanRegistryNameScanParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostScanRegistryNameScanParamsWithTimeout creates a new PostScanRegistryNameScanParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostScanRegistryNameScanParamsWithTimeout(timeout time.Duration) *PostScanRegistryNameScanParams {
	var ()
	return &PostScanRegistryNameScanParams{

		timeout: timeout,
	}
}

// NewPostScanRegistryNameScanParamsWithContext creates a new PostScanRegistryNameScanParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostScanRegistryNameScanParamsWithContext(ctx context.Context) *PostScanRegistryNameScanParams {
	var ()
	return &PostScanRegistryNameScanParams{

		Context: ctx,
	}
}

// NewPostScanRegistryNameScanParamsWithHTTPClient creates a new PostScanRegistryNameScanParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostScanRegistryNameScanParamsWithHTTPClient(client *http.Client) *PostScanRegistryNameScanParams {
	var ()
	return &PostScanRegistryNameScanParams{
		HTTPClient: client,
	}
}

/*PostScanRegistryNameScanParams contains all the parameters to send to the API endpoint
for the post scan registry name scan operation typically these are written to a http.Request
*/
type PostScanRegistryNameScanParams struct {

	/*XAuthToken*/
	XAuthToken string
	/*Name
	  Name of the registry

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post scan registry name scan params
func (o *PostScanRegistryNameScanParams) WithTimeout(timeout time.Duration) *PostScanRegistryNameScanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post scan registry name scan params
func (o *PostScanRegistryNameScanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post scan registry name scan params
func (o *PostScanRegistryNameScanParams) WithContext(ctx context.Context) *PostScanRegistryNameScanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post scan registry name scan params
func (o *PostScanRegistryNameScanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post scan registry name scan params
func (o *PostScanRegistryNameScanParams) WithHTTPClient(client *http.Client) *PostScanRegistryNameScanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post scan registry name scan params
func (o *PostScanRegistryNameScanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the post scan registry name scan params
func (o *PostScanRegistryNameScanParams) WithXAuthToken(xAuthToken string) *PostScanRegistryNameScanParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the post scan registry name scan params
func (o *PostScanRegistryNameScanParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithName adds the name to the post scan registry name scan params
func (o *PostScanRegistryNameScanParams) WithName(name string) *PostScanRegistryNameScanParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the post scan registry name scan params
func (o *PostScanRegistryNameScanParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PostScanRegistryNameScanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
