// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostScanPlatformPlatformReader is a Reader for the PostScanPlatformPlatform structure.
type PostScanPlatformPlatformReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostScanPlatformPlatformReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostScanPlatformPlatformOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostScanPlatformPlatformOK creates a PostScanPlatformPlatformOK with default headers values
func NewPostScanPlatformPlatformOK() *PostScanPlatformPlatformOK {
	return &PostScanPlatformPlatformOK{}
}

/*PostScanPlatformPlatformOK handles this case with default header values.

Success
*/
type PostScanPlatformPlatformOK struct {
}

func (o *PostScanPlatformPlatformOK) Error() string {
	return fmt.Sprintf("[POST /scan/platform/platform][%d] postScanPlatformPlatformOK ", 200)
}

func (o *PostScanPlatformPlatformOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
