// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/neuvector/models"
)

// PostScanRepositoryReader is a Reader for the PostScanRepository structure.
type PostScanRepositoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostScanRepositoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostScanRepositoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostScanRepositoryOK creates a PostScanRepositoryOK with default headers values
func NewPostScanRepositoryOK() *PostScanRepositoryOK {
	return &PostScanRepositoryOK{}
}

/*PostScanRepositoryOK handles this case with default header values.

Success
*/
type PostScanRepositoryOK struct {
	Payload *models.RESTScanRepoReportData
}

func (o *PostScanRepositoryOK) Error() string {
	return fmt.Sprintf("[POST /scan/repository][%d] postScanRepositoryOK  %+v", 200, o.Payload)
}

func (o *PostScanRepositoryOK) GetPayload() *models.RESTScanRepoReportData {
	return o.Payload
}

func (o *PostScanRepositoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTScanRepoReportData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
