// Code generated by go-swagger; DO NOT EDIT.

package response_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteResponseRuleIDParams creates a new DeleteResponseRuleIDParams object
// with the default values initialized.
func NewDeleteResponseRuleIDParams() *DeleteResponseRuleIDParams {
	var ()
	return &DeleteResponseRuleIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteResponseRuleIDParamsWithTimeout creates a new DeleteResponseRuleIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteResponseRuleIDParamsWithTimeout(timeout time.Duration) *DeleteResponseRuleIDParams {
	var ()
	return &DeleteResponseRuleIDParams{

		timeout: timeout,
	}
}

// NewDeleteResponseRuleIDParamsWithContext creates a new DeleteResponseRuleIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteResponseRuleIDParamsWithContext(ctx context.Context) *DeleteResponseRuleIDParams {
	var ()
	return &DeleteResponseRuleIDParams{

		Context: ctx,
	}
}

// NewDeleteResponseRuleIDParamsWithHTTPClient creates a new DeleteResponseRuleIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteResponseRuleIDParamsWithHTTPClient(client *http.Client) *DeleteResponseRuleIDParams {
	var ()
	return &DeleteResponseRuleIDParams{
		HTTPClient: client,
	}
}

/*DeleteResponseRuleIDParams contains all the parameters to send to the API endpoint
for the delete response rule ID operation typically these are written to a http.Request
*/
type DeleteResponseRuleIDParams struct {

	/*XAuthToken*/
	XAuthToken string
	/*ID
	  Rule ID

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete response rule ID params
func (o *DeleteResponseRuleIDParams) WithTimeout(timeout time.Duration) *DeleteResponseRuleIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete response rule ID params
func (o *DeleteResponseRuleIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete response rule ID params
func (o *DeleteResponseRuleIDParams) WithContext(ctx context.Context) *DeleteResponseRuleIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete response rule ID params
func (o *DeleteResponseRuleIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete response rule ID params
func (o *DeleteResponseRuleIDParams) WithHTTPClient(client *http.Client) *DeleteResponseRuleIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete response rule ID params
func (o *DeleteResponseRuleIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the delete response rule ID params
func (o *DeleteResponseRuleIDParams) WithXAuthToken(xAuthToken string) *DeleteResponseRuleIDParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the delete response rule ID params
func (o *DeleteResponseRuleIDParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithID adds the id to the delete response rule ID params
func (o *DeleteResponseRuleIDParams) WithID(id string) *DeleteResponseRuleIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete response rule ID params
func (o *DeleteResponseRuleIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteResponseRuleIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
