// Code generated by go-swagger; DO NOT EDIT.

package response_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteResponseRuleReader is a Reader for the DeleteResponseRule structure.
type DeleteResponseRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteResponseRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteResponseRuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteResponseRuleOK creates a DeleteResponseRuleOK with default headers values
func NewDeleteResponseRuleOK() *DeleteResponseRuleOK {
	return &DeleteResponseRuleOK{}
}

/*DeleteResponseRuleOK handles this case with default header values.

Success
*/
type DeleteResponseRuleOK struct {
}

func (o *DeleteResponseRuleOK) Error() string {
	return fmt.Sprintf("[DELETE /response/rule][%d] deleteResponseRuleOK ", 200)
}

func (o *DeleteResponseRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
