// Code generated by go-swagger; DO NOT EDIT.

package response_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetResponseRuleIDParams creates a new GetResponseRuleIDParams object
// with the default values initialized.
func NewGetResponseRuleIDParams() *GetResponseRuleIDParams {
	var ()
	return &GetResponseRuleIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetResponseRuleIDParamsWithTimeout creates a new GetResponseRuleIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetResponseRuleIDParamsWithTimeout(timeout time.Duration) *GetResponseRuleIDParams {
	var ()
	return &GetResponseRuleIDParams{

		timeout: timeout,
	}
}

// NewGetResponseRuleIDParamsWithContext creates a new GetResponseRuleIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetResponseRuleIDParamsWithContext(ctx context.Context) *GetResponseRuleIDParams {
	var ()
	return &GetResponseRuleIDParams{

		Context: ctx,
	}
}

// NewGetResponseRuleIDParamsWithHTTPClient creates a new GetResponseRuleIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetResponseRuleIDParamsWithHTTPClient(client *http.Client) *GetResponseRuleIDParams {
	var ()
	return &GetResponseRuleIDParams{
		HTTPClient: client,
	}
}

/*GetResponseRuleIDParams contains all the parameters to send to the API endpoint
for the get response rule ID operation typically these are written to a http.Request
*/
type GetResponseRuleIDParams struct {

	/*XAuthToken*/
	XAuthToken string
	/*ID
	  Rule ID

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get response rule ID params
func (o *GetResponseRuleIDParams) WithTimeout(timeout time.Duration) *GetResponseRuleIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get response rule ID params
func (o *GetResponseRuleIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get response rule ID params
func (o *GetResponseRuleIDParams) WithContext(ctx context.Context) *GetResponseRuleIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get response rule ID params
func (o *GetResponseRuleIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get response rule ID params
func (o *GetResponseRuleIDParams) WithHTTPClient(client *http.Client) *GetResponseRuleIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get response rule ID params
func (o *GetResponseRuleIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get response rule ID params
func (o *GetResponseRuleIDParams) WithXAuthToken(xAuthToken string) *GetResponseRuleIDParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get response rule ID params
func (o *GetResponseRuleIDParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithID adds the id to the get response rule ID params
func (o *GetResponseRuleIDParams) WithID(id string) *GetResponseRuleIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get response rule ID params
func (o *GetResponseRuleIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetResponseRuleIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
