// Code generated by go-swagger; DO NOT EDIT.

package response_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetResponseWorkloadRulesIDParams creates a new GetResponseWorkloadRulesIDParams object
// with the default values initialized.
func NewGetResponseWorkloadRulesIDParams() *GetResponseWorkloadRulesIDParams {
	var ()
	return &GetResponseWorkloadRulesIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetResponseWorkloadRulesIDParamsWithTimeout creates a new GetResponseWorkloadRulesIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetResponseWorkloadRulesIDParamsWithTimeout(timeout time.Duration) *GetResponseWorkloadRulesIDParams {
	var ()
	return &GetResponseWorkloadRulesIDParams{

		timeout: timeout,
	}
}

// NewGetResponseWorkloadRulesIDParamsWithContext creates a new GetResponseWorkloadRulesIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetResponseWorkloadRulesIDParamsWithContext(ctx context.Context) *GetResponseWorkloadRulesIDParams {
	var ()
	return &GetResponseWorkloadRulesIDParams{

		Context: ctx,
	}
}

// NewGetResponseWorkloadRulesIDParamsWithHTTPClient creates a new GetResponseWorkloadRulesIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetResponseWorkloadRulesIDParamsWithHTTPClient(client *http.Client) *GetResponseWorkloadRulesIDParams {
	var ()
	return &GetResponseWorkloadRulesIDParams{
		HTTPClient: client,
	}
}

/*GetResponseWorkloadRulesIDParams contains all the parameters to send to the API endpoint
for the get response workload rules ID operation typically these are written to a http.Request
*/
type GetResponseWorkloadRulesIDParams struct {

	/*XAuthToken*/
	XAuthToken string
	/*ID
	  Workload rules ID

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get response workload rules ID params
func (o *GetResponseWorkloadRulesIDParams) WithTimeout(timeout time.Duration) *GetResponseWorkloadRulesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get response workload rules ID params
func (o *GetResponseWorkloadRulesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get response workload rules ID params
func (o *GetResponseWorkloadRulesIDParams) WithContext(ctx context.Context) *GetResponseWorkloadRulesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get response workload rules ID params
func (o *GetResponseWorkloadRulesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get response workload rules ID params
func (o *GetResponseWorkloadRulesIDParams) WithHTTPClient(client *http.Client) *GetResponseWorkloadRulesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get response workload rules ID params
func (o *GetResponseWorkloadRulesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the get response workload rules ID params
func (o *GetResponseWorkloadRulesIDParams) WithXAuthToken(xAuthToken string) *GetResponseWorkloadRulesIDParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the get response workload rules ID params
func (o *GetResponseWorkloadRulesIDParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithID adds the id to the get response workload rules ID params
func (o *GetResponseWorkloadRulesIDParams) WithID(id string) *GetResponseWorkloadRulesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get response workload rules ID params
func (o *GetResponseWorkloadRulesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetResponseWorkloadRulesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
