// Code generated by go-swagger; DO NOT EDIT.

package response_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/neuvector/models"
)

// GetResponseRuleReader is a Reader for the GetResponseRule structure.
type GetResponseRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetResponseRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetResponseRuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetResponseRuleOK creates a GetResponseRuleOK with default headers values
func NewGetResponseRuleOK() *GetResponseRuleOK {
	return &GetResponseRuleOK{}
}

/*GetResponseRuleOK handles this case with default header values.

Success
*/
type GetResponseRuleOK struct {
	Payload *models.RESTResponseRulesData
}

func (o *GetResponseRuleOK) Error() string {
	return fmt.Sprintf("[GET /response/rule][%d] getResponseRuleOK  %+v", 200, o.Payload)
}

func (o *GetResponseRuleOK) GetPayload() *models.RESTResponseRulesData {
	return o.Payload
}

func (o *GetResponseRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTResponseRulesData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
