// Code generated by go-swagger; DO NOT EDIT.

package response_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PatchResponseRuleIDReader is a Reader for the PatchResponseRuleID structure.
type PatchResponseRuleIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchResponseRuleIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchResponseRuleIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchResponseRuleIDOK creates a PatchResponseRuleIDOK with default headers values
func NewPatchResponseRuleIDOK() *PatchResponseRuleIDOK {
	return &PatchResponseRuleIDOK{}
}

/*PatchResponseRuleIDOK handles this case with default header values.

Success
*/
type PatchResponseRuleIDOK struct {
}

func (o *PatchResponseRuleIDOK) Error() string {
	return fmt.Sprintf("[PATCH /response/rule/{id}][%d] patchResponseRuleIdOK ", 200)
}

func (o *PatchResponseRuleIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
