// Code generated by go-swagger; DO NOT EDIT.

package response_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/neuvector/models"
)

// NewPatchResponseRuleIDParams creates a new PatchResponseRuleIDParams object
// with the default values initialized.
func NewPatchResponseRuleIDParams() *PatchResponseRuleIDParams {
	var ()
	return &PatchResponseRuleIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchResponseRuleIDParamsWithTimeout creates a new PatchResponseRuleIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchResponseRuleIDParamsWithTimeout(timeout time.Duration) *PatchResponseRuleIDParams {
	var ()
	return &PatchResponseRuleIDParams{

		timeout: timeout,
	}
}

// NewPatchResponseRuleIDParamsWithContext creates a new PatchResponseRuleIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchResponseRuleIDParamsWithContext(ctx context.Context) *PatchResponseRuleIDParams {
	var ()
	return &PatchResponseRuleIDParams{

		Context: ctx,
	}
}

// NewPatchResponseRuleIDParamsWithHTTPClient creates a new PatchResponseRuleIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchResponseRuleIDParamsWithHTTPClient(client *http.Client) *PatchResponseRuleIDParams {
	var ()
	return &PatchResponseRuleIDParams{
		HTTPClient: client,
	}
}

/*PatchResponseRuleIDParams contains all the parameters to send to the API endpoint
for the patch response rule ID operation typically these are written to a http.Request
*/
type PatchResponseRuleIDParams struct {

	/*XAuthToken*/
	XAuthToken string
	/*Body
	  Response rule data

	*/
	Body *models.RESTResponseRuleConfigData
	/*ID
	  Rule ID

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch response rule ID params
func (o *PatchResponseRuleIDParams) WithTimeout(timeout time.Duration) *PatchResponseRuleIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch response rule ID params
func (o *PatchResponseRuleIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch response rule ID params
func (o *PatchResponseRuleIDParams) WithContext(ctx context.Context) *PatchResponseRuleIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch response rule ID params
func (o *PatchResponseRuleIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch response rule ID params
func (o *PatchResponseRuleIDParams) WithHTTPClient(client *http.Client) *PatchResponseRuleIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch response rule ID params
func (o *PatchResponseRuleIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the patch response rule ID params
func (o *PatchResponseRuleIDParams) WithXAuthToken(xAuthToken string) *PatchResponseRuleIDParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the patch response rule ID params
func (o *PatchResponseRuleIDParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithBody adds the body to the patch response rule ID params
func (o *PatchResponseRuleIDParams) WithBody(body *models.RESTResponseRuleConfigData) *PatchResponseRuleIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch response rule ID params
func (o *PatchResponseRuleIDParams) SetBody(body *models.RESTResponseRuleConfigData) {
	o.Body = body
}

// WithID adds the id to the patch response rule ID params
func (o *PatchResponseRuleIDParams) WithID(id string) *PatchResponseRuleIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch response rule ID params
func (o *PatchResponseRuleIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchResponseRuleIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
