// Code generated by go-swagger; DO NOT EDIT.

package response_rule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PatchResponseRuleReader is a Reader for the PatchResponseRule structure.
type PatchResponseRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchResponseRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchResponseRuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchResponseRuleOK creates a PatchResponseRuleOK with default headers values
func NewPatchResponseRuleOK() *PatchResponseRuleOK {
	return &PatchResponseRuleOK{}
}

/*PatchResponseRuleOK handles this case with default header values.

Success
*/
type PatchResponseRuleOK struct {
}

func (o *PatchResponseRuleOK) Error() string {
	return fmt.Sprintf("[PATCH /response/rule][%d] patchResponseRuleOK ", 200)
}

func (o *PatchResponseRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
