// Code generated by go-swagger; DO NOT EDIT.

package e_u_l_a

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new e u l a API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for e u l a API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetEula(params *GetEulaParams) (*GetEulaOK, error)

	PostEula(params *PostEulaParams) (*PostEulaOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetEula gets e u l a agreement acceptance status
*/
func (a *Client) GetEula(params *GetEulaParams) (*GetEulaOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetEulaParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetEula",
		Method:             "GET",
		PathPattern:        "/eula",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetEulaReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetEulaOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetEula: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostEula accepts e u l a agreement
*/
func (a *Client) PostEula(params *PostEulaParams) (*PostEulaOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostEulaParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostEula",
		Method:             "POST",
		PathPattern:        "/eula",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostEulaReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostEulaOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostEula: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
