// Code generated by go-swagger; DO NOT EDIT.

package e_u_l_a

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/neuvector/models"
)

// GetEulaReader is a Reader for the GetEula structure.
type GetEulaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEulaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEulaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetEulaOK creates a GetEulaOK with default headers values
func NewGetEulaOK() *GetEulaOK {
	return &GetEulaOK{}
}

/*GetEulaOK handles this case with default header values.

Success
*/
type GetEulaOK struct {
	Payload *models.RESTEULAData
}

func (o *GetEulaOK) Error() string {
	return fmt.Sprintf("[GET /eula][%d] getEulaOK  %+v", 200, o.Payload)
}

func (o *GetEulaOK) GetPayload() *models.RESTEULAData {
	return o.Payload
}

func (o *GetEulaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTEULAData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
