// Code generated by go-swagger; DO NOT EDIT.

package third_party_scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/nexusiq/models"
)

// GetScanStatusReader is a Reader for the GetScanStatus structure.
type GetScanStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScanStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScanStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetScanStatusUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetScanStatusOK creates a GetScanStatusOK with default headers values
func NewGetScanStatusOK() *GetScanStatusOK {
	return &GetScanStatusOK{}
}

/*GetScanStatusOK handles this case with default header values.

OK
*/
type GetScanStatusOK struct {
	Payload *models.ScanStatus
}

func (o *GetScanStatusOK) Error() string {
	return fmt.Sprintf("[GET /scan/applications/{applicationInternalId}/status/{statusId}][%d] getScanStatusOK  %+v", 200, o.Payload)
}

func (o *GetScanStatusOK) GetPayload() *models.ScanStatus {
	return o.Payload
}

func (o *GetScanStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ScanStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetScanStatusUnauthorized creates a GetScanStatusUnauthorized with default headers values
func NewGetScanStatusUnauthorized() *GetScanStatusUnauthorized {
	return &GetScanStatusUnauthorized{}
}

/*GetScanStatusUnauthorized handles this case with default header values.

Unauthorized
*/
type GetScanStatusUnauthorized struct {
}

func (o *GetScanStatusUnauthorized) Error() string {
	return fmt.Sprintf("[GET /scan/applications/{applicationInternalId}/status/{statusId}][%d] getScanStatusUnauthorized ", 401)
}

func (o *GetScanStatusUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
