// Code generated by go-swagger; DO NOT EDIT.

package third_party_scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostScanParams creates a new PostScanParams object
// with the default values initialized.
func NewPostScanParams() *PostScanParams {
	var ()
	return &PostScanParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostScanParamsWithTimeout creates a new PostScanParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostScanParamsWithTimeout(timeout time.Duration) *PostScanParams {
	var ()
	return &PostScanParams{

		timeout: timeout,
	}
}

// NewPostScanParamsWithContext creates a new PostScanParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostScanParamsWithContext(ctx context.Context) *PostScanParams {
	var ()
	return &PostScanParams{

		Context: ctx,
	}
}

// NewPostScanParamsWithHTTPClient creates a new PostScanParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostScanParamsWithHTTPClient(client *http.Client) *PostScanParams {
	var ()
	return &PostScanParams{
		HTTPClient: client,
	}
}

/*PostScanParams contains all the parameters to send to the API endpoint
for the post scan operation typically these are written to a http.Request
*/
type PostScanParams struct {

	/*ApplicationInternalID
	  Internal application ID


	*/
	ApplicationInternalID string
	/*Bom
	  CycloneDX SBOM XML

	*/
	Bom interface{}
	/*Source
	  Source

	*/
	Source string
	/*StageID
	  The stageId query param is optional, if not sent build is used by default. Accepted values are develop, build, stage-release, release, and operate.


	*/
	StageID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post scan params
func (o *PostScanParams) WithTimeout(timeout time.Duration) *PostScanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post scan params
func (o *PostScanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post scan params
func (o *PostScanParams) WithContext(ctx context.Context) *PostScanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post scan params
func (o *PostScanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post scan params
func (o *PostScanParams) WithHTTPClient(client *http.Client) *PostScanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post scan params
func (o *PostScanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApplicationInternalID adds the applicationInternalID to the post scan params
func (o *PostScanParams) WithApplicationInternalID(applicationInternalID string) *PostScanParams {
	o.SetApplicationInternalID(applicationInternalID)
	return o
}

// SetApplicationInternalID adds the applicationInternalId to the post scan params
func (o *PostScanParams) SetApplicationInternalID(applicationInternalID string) {
	o.ApplicationInternalID = applicationInternalID
}

// WithBom adds the bom to the post scan params
func (o *PostScanParams) WithBom(bom interface{}) *PostScanParams {
	o.SetBom(bom)
	return o
}

// SetBom adds the bom to the post scan params
func (o *PostScanParams) SetBom(bom interface{}) {
	o.Bom = bom
}

// WithSource adds the source to the post scan params
func (o *PostScanParams) WithSource(source string) *PostScanParams {
	o.SetSource(source)
	return o
}

// SetSource adds the source to the post scan params
func (o *PostScanParams) SetSource(source string) {
	o.Source = source
}

// WithStageID adds the stageID to the post scan params
func (o *PostScanParams) WithStageID(stageID *string) *PostScanParams {
	o.SetStageID(stageID)
	return o
}

// SetStageID adds the stageId to the post scan params
func (o *PostScanParams) SetStageID(stageID *string) {
	o.StageID = stageID
}

// WriteToRequest writes these params to a swagger request
func (o *PostScanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param applicationInternalId
	if err := r.SetPathParam("applicationInternalId", o.ApplicationInternalID); err != nil {
		return err
	}

	if o.Bom != nil {
		if err := r.SetBodyParam(o.Bom); err != nil {
			return err
		}
	}

	// path param source
	if err := r.SetPathParam("source", o.Source); err != nil {
		return err
	}

	if o.StageID != nil {

		// query param stageId
		var qrStageID string
		if o.StageID != nil {
			qrStageID = *o.StageID
		}
		qStageID := qrStageID
		if qStageID != "" {
			if err := r.SetQueryParam("stageId", qStageID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
