// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteSystemLicenseParams creates a new DeleteSystemLicenseParams object
// with the default values initialized.
func NewDeleteSystemLicenseParams() *DeleteSystemLicenseParams {
	var ()
	return &DeleteSystemLicenseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSystemLicenseParamsWithTimeout creates a new DeleteSystemLicenseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSystemLicenseParamsWithTimeout(timeout time.Duration) *DeleteSystemLicenseParams {
	var ()
	return &DeleteSystemLicenseParams{

		timeout: timeout,
	}
}

// NewDeleteSystemLicenseParamsWithContext creates a new DeleteSystemLicenseParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSystemLicenseParamsWithContext(ctx context.Context) *DeleteSystemLicenseParams {
	var ()
	return &DeleteSystemLicenseParams{

		Context: ctx,
	}
}

// NewDeleteSystemLicenseParamsWithHTTPClient creates a new DeleteSystemLicenseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSystemLicenseParamsWithHTTPClient(client *http.Client) *DeleteSystemLicenseParams {
	var ()
	return &DeleteSystemLicenseParams{
		HTTPClient: client,
	}
}

/*DeleteSystemLicenseParams contains all the parameters to send to the API endpoint
for the delete system license operation typically these are written to a http.Request
*/
type DeleteSystemLicenseParams struct {

	/*XAuthToken*/
	XAuthToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete system license params
func (o *DeleteSystemLicenseParams) WithTimeout(timeout time.Duration) *DeleteSystemLicenseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete system license params
func (o *DeleteSystemLicenseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete system license params
func (o *DeleteSystemLicenseParams) WithContext(ctx context.Context) *DeleteSystemLicenseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete system license params
func (o *DeleteSystemLicenseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete system license params
func (o *DeleteSystemLicenseParams) WithHTTPClient(client *http.Client) *DeleteSystemLicenseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete system license params
func (o *DeleteSystemLicenseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the delete system license params
func (o *DeleteSystemLicenseParams) WithXAuthToken(xAuthToken string) *DeleteSystemLicenseParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the delete system license params
func (o *DeleteSystemLicenseParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSystemLicenseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
