// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteSystemLicenseReader is a Reader for the DeleteSystemLicense structure.
type DeleteSystemLicenseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSystemLicenseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSystemLicenseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteSystemLicenseOK creates a DeleteSystemLicenseOK with default headers values
func NewDeleteSystemLicenseOK() *DeleteSystemLicenseOK {
	return &DeleteSystemLicenseOK{}
}

/*DeleteSystemLicenseOK handles this case with default header values.

Success
*/
type DeleteSystemLicenseOK struct {
}

func (o *DeleteSystemLicenseOK) Error() string {
	return fmt.Sprintf("[DELETE /system/license][%d] deleteSystemLicenseOK ", 200)
}

func (o *DeleteSystemLicenseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
