// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/neuvector/models"
)

// GetSystemConfigReader is a Reader for the GetSystemConfig structure.
type GetSystemConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSystemConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSystemConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSystemConfigOK creates a GetSystemConfigOK with default headers values
func NewGetSystemConfigOK() *GetSystemConfigOK {
	return &GetSystemConfigOK{}
}

/*GetSystemConfigOK handles this case with default header values.

Success
*/
type GetSystemConfigOK struct {
	Payload *models.RESTSystemConfigData
}

func (o *GetSystemConfigOK) Error() string {
	return fmt.Sprintf("[GET /system/config][%d] getSystemConfigOK  %+v", 200, o.Payload)
}

func (o *GetSystemConfigOK) GetPayload() *models.RESTSystemConfigData {
	return o.Payload
}

func (o *GetSystemConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTSystemConfigData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
