// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/neuvector/models"
)

// GetSystemSummaryReader is a Reader for the GetSystemSummary structure.
type GetSystemSummaryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSystemSummaryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSystemSummaryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSystemSummaryOK creates a GetSystemSummaryOK with default headers values
func NewGetSystemSummaryOK() *GetSystemSummaryOK {
	return &GetSystemSummaryOK{}
}

/*GetSystemSummaryOK handles this case with default header values.

Success
*/
type GetSystemSummaryOK struct {
	Payload *models.RESTSystemSummaryData
}

func (o *GetSystemSummaryOK) Error() string {
	return fmt.Sprintf("[GET /system/summary][%d] getSystemSummaryOK  %+v", 200, o.Payload)
}

func (o *GetSystemSummaryOK) GetPayload() *models.RESTSystemSummaryData {
	return o.Payload
}

func (o *GetSystemSummaryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RESTSystemSummaryData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
