// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PatchSystemConfigReader is a Reader for the PatchSystemConfig structure.
type PatchSystemConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchSystemConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchSystemConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchSystemConfigOK creates a PatchSystemConfigOK with default headers values
func NewPatchSystemConfigOK() *PatchSystemConfigOK {
	return &PatchSystemConfigOK{}
}

/*PatchSystemConfigOK handles this case with default header values.

Success
*/
type PatchSystemConfigOK struct {
}

func (o *PatchSystemConfigOK) Error() string {
	return fmt.Sprintf("[PATCH /system/config][%d] patchSystemConfigOK ", 200)
}

func (o *PatchSystemConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
