// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostSystemRequestReader is a Reader for the PostSystemRequest structure.
type PostSystemRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSystemRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostSystemRequestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostSystemRequestOK creates a PostSystemRequestOK with default headers values
func NewPostSystemRequestOK() *PostSystemRequestOK {
	return &PostSystemRequestOK{}
}

/*PostSystemRequestOK handles this case with default header values.

Success
*/
type PostSystemRequestOK struct {
}

func (o *PostSystemRequestOK) Error() string {
	return fmt.Sprintf("[POST /system/request][%d] postSystemRequestOK ", 200)
}

func (o *PostSystemRequestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
