// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostSystemLicenseUpdateReader is a Reader for the PostSystemLicenseUpdate structure.
type PostSystemLicenseUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSystemLicenseUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostSystemLicenseUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostSystemLicenseUpdateOK creates a PostSystemLicenseUpdateOK with default headers values
func NewPostSystemLicenseUpdateOK() *PostSystemLicenseUpdateOK {
	return &PostSystemLicenseUpdateOK{}
}

/*PostSystemLicenseUpdateOK handles this case with default header values.

Success
*/
type PostSystemLicenseUpdateOK struct {
}

func (o *PostSystemLicenseUpdateOK) Error() string {
	return fmt.Sprintf("[POST /system/license/update][%d] postSystemLicenseUpdateOK ", 200)
}

func (o *PostSystemLicenseUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
