// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostSystemLicenseRequestReader is a Reader for the PostSystemLicenseRequest structure.
type PostSystemLicenseRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSystemLicenseRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostSystemLicenseRequestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostSystemLicenseRequestOK creates a PostSystemLicenseRequestOK with default headers values
func NewPostSystemLicenseRequestOK() *PostSystemLicenseRequestOK {
	return &PostSystemLicenseRequestOK{}
}

/*PostSystemLicenseRequestOK handles this case with default header values.

Success
*/
type PostSystemLicenseRequestOK struct {
}

func (o *PostSystemLicenseRequestOK) Error() string {
	return fmt.Sprintf("[POST /system/license/request][%d] postSystemLicenseRequestOK ", 200)
}

func (o *PostSystemLicenseRequestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
