// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/neuvector/models"
)

// NewPostSystemLicenseRequestParams creates a new PostSystemLicenseRequestParams object
// with the default values initialized.
func NewPostSystemLicenseRequestParams() *PostSystemLicenseRequestParams {
	var ()
	return &PostSystemLicenseRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostSystemLicenseRequestParamsWithTimeout creates a new PostSystemLicenseRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostSystemLicenseRequestParamsWithTimeout(timeout time.Duration) *PostSystemLicenseRequestParams {
	var ()
	return &PostSystemLicenseRequestParams{

		timeout: timeout,
	}
}

// NewPostSystemLicenseRequestParamsWithContext creates a new PostSystemLicenseRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostSystemLicenseRequestParamsWithContext(ctx context.Context) *PostSystemLicenseRequestParams {
	var ()
	return &PostSystemLicenseRequestParams{

		Context: ctx,
	}
}

// NewPostSystemLicenseRequestParamsWithHTTPClient creates a new PostSystemLicenseRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostSystemLicenseRequestParamsWithHTTPClient(client *http.Client) *PostSystemLicenseRequestParams {
	var ()
	return &PostSystemLicenseRequestParams{
		HTTPClient: client,
	}
}

/*PostSystemLicenseRequestParams contains all the parameters to send to the API endpoint
for the post system license request operation typically these are written to a http.Request
*/
type PostSystemLicenseRequestParams struct {

	/*XAuthToken*/
	XAuthToken string
	/*Body
	  License request data

	*/
	Body *models.RESTLicenseRequestData

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post system license request params
func (o *PostSystemLicenseRequestParams) WithTimeout(timeout time.Duration) *PostSystemLicenseRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post system license request params
func (o *PostSystemLicenseRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post system license request params
func (o *PostSystemLicenseRequestParams) WithContext(ctx context.Context) *PostSystemLicenseRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post system license request params
func (o *PostSystemLicenseRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post system license request params
func (o *PostSystemLicenseRequestParams) WithHTTPClient(client *http.Client) *PostSystemLicenseRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post system license request params
func (o *PostSystemLicenseRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the post system license request params
func (o *PostSystemLicenseRequestParams) WithXAuthToken(xAuthToken string) *PostSystemLicenseRequestParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the post system license request params
func (o *PostSystemLicenseRequestParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WithBody adds the body to the post system license request params
func (o *PostSystemLicenseRequestParams) WithBody(body *models.RESTLicenseRequestData) *PostSystemLicenseRequestParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post system license request params
func (o *PostSystemLicenseRequestParams) SetBody(body *models.RESTLicenseRequestData) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostSystemLicenseRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
