// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// License license
//
// swagger:model License
type License struct {

	// application limit to display
	ApplicationLimitToDisplay int64 `json:"applicationLimitToDisplay,omitempty"`

	// contact company
	ContactCompany string `json:"contactCompany,omitempty"`

	// contact email
	ContactEmail string `json:"contactEmail,omitempty"`

	// contact name
	ContactName string `json:"contactName,omitempty"`

	// expiry timestamp
	ExpiryTimestamp int64 `json:"expiryTimestamp,omitempty"`

	// fingerprint
	Fingerprint string `json:"fingerprint,omitempty"`

	// firewall users to display
	FirewallUsersToDisplay int64 `json:"firewallUsersToDisplay,omitempty"`

	// licensed users to display
	LicensedUsersToDisplay int64 `json:"licensedUsersToDisplay,omitempty"`

	// product edition
	ProductEdition string `json:"productEdition,omitempty"`

	// products
	Products []string `json:"products"`
}

// Validate validates this license
func (m *License) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *License) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *License) UnmarshalBinary(b []byte) error {
	var res License
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
