// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPatchAuthParams creates a new PatchAuthParams object
// with the default values initialized.
func NewPatchAuthParams() *PatchAuthParams {
	var ()
	return &PatchAuthParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAuthParamsWithTimeout creates a new PatchAuthParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchAuthParamsWithTimeout(timeout time.Duration) *PatchAuthParams {
	var ()
	return &PatchAuthParams{

		timeout: timeout,
	}
}

// NewPatchAuthParamsWithContext creates a new PatchAuthParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchAuthParamsWithContext(ctx context.Context) *PatchAuthParams {
	var ()
	return &PatchAuthParams{

		Context: ctx,
	}
}

// NewPatchAuthParamsWithHTTPClient creates a new PatchAuthParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchAuthParamsWithHTTPClient(client *http.Client) *PatchAuthParams {
	var ()
	return &PatchAuthParams{
		HTTPClient: client,
	}
}

/*PatchAuthParams contains all the parameters to send to the API endpoint
for the patch auth operation typically these are written to a http.Request
*/
type PatchAuthParams struct {

	/*XAuthToken*/
	XAuthToken string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch auth params
func (o *PatchAuthParams) WithTimeout(timeout time.Duration) *PatchAuthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch auth params
func (o *PatchAuthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch auth params
func (o *PatchAuthParams) WithContext(ctx context.Context) *PatchAuthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch auth params
func (o *PatchAuthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch auth params
func (o *PatchAuthParams) WithHTTPClient(client *http.Client) *PatchAuthParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch auth params
func (o *PatchAuthParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXAuthToken adds the xAuthToken to the patch auth params
func (o *PatchAuthParams) WithXAuthToken(xAuthToken string) *PatchAuthParams {
	o.SetXAuthToken(xAuthToken)
	return o
}

// SetXAuthToken adds the xAuthToken to the patch auth params
func (o *PatchAuthParams) SetXAuthToken(xAuthToken string) {
	o.XAuthToken = xAuthToken
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAuthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Auth-Token
	if err := r.SetHeaderParam("X-Auth-Token", o.XAuthToken); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
