// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostAuthServerReader is a Reader for the PostAuthServer structure.
type PostAuthServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAuthServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAuthServerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAuthServerOK creates a PostAuthServerOK with default headers values
func NewPostAuthServerOK() *PostAuthServerOK {
	return &PostAuthServerOK{}
}

/*PostAuthServerOK handles this case with default header values.

Success
*/
type PostAuthServerOK struct {
}

func (o *PostAuthServerOK) Error() string {
	return fmt.Sprintf("[POST /auth/{server}][%d] postAuthServerOK ", 200)
}

func (o *PostAuthServerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
