// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/neuvector/neuvector-nexus-iq/nexusiq/models"
)

// CreateApplicationReader is a Reader for the CreateApplication structure.
type CreateApplicationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateApplicationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateApplicationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateApplicationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateApplicationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateApplicationOK creates a CreateApplicationOK with default headers values
func NewCreateApplicationOK() *CreateApplicationOK {
	return &CreateApplicationOK{}
}

/*CreateApplicationOK handles this case with default header values.

Created
*/
type CreateApplicationOK struct {
	Payload *models.Application
}

func (o *CreateApplicationOK) Error() string {
	return fmt.Sprintf("[POST /applications][%d] createApplicationOK  %+v", 200, o.Payload)
}

func (o *CreateApplicationOK) GetPayload() *models.Application {
	return o.Payload
}

func (o *CreateApplicationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Application)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateApplicationBadRequest creates a CreateApplicationBadRequest with default headers values
func NewCreateApplicationBadRequest() *CreateApplicationBadRequest {
	return &CreateApplicationBadRequest{}
}

/*CreateApplicationBadRequest handles this case with default header values.

BadRequest
*/
type CreateApplicationBadRequest struct {
}

func (o *CreateApplicationBadRequest) Error() string {
	return fmt.Sprintf("[POST /applications][%d] createApplicationBadRequest ", 400)
}

func (o *CreateApplicationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateApplicationUnauthorized creates a CreateApplicationUnauthorized with default headers values
func NewCreateApplicationUnauthorized() *CreateApplicationUnauthorized {
	return &CreateApplicationUnauthorized{}
}

/*CreateApplicationUnauthorized handles this case with default header values.

Unauthorized
*/
type CreateApplicationUnauthorized struct {
}

func (o *CreateApplicationUnauthorized) Error() string {
	return fmt.Sprintf("[POST /applications][%d] createApplicationUnauthorized ", 401)
}

func (o *CreateApplicationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
