// Code generated by go-swagger; DO NOT EDIT.

package license

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SetLicenseReader is a Reader for the SetLicense structure.
type SetLicenseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetLicenseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetLicenseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetLicenseOK creates a SetLicenseOK with default headers values
func NewSetLicenseOK() *SetLicenseOK {
	return &SetLicenseOK{}
}

/*SetLicenseOK handles this case with default header values.

OK
*/
type SetLicenseOK struct {
}

func (o *SetLicenseOK) Error() string {
	return fmt.Sprintf("[POST /rest/product/license][%d] setLicenseOK ", 200)
}

func (o *SetLicenseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
