name: Build

# Trigger on push to all branches and on pull requests
on:
  push:
  pull_request:

jobs:
  build:
    # Run on GitHub hosted runner Ubuntu 18.04
    runs-on: ubuntu-18.04

    env:
      IMAGE_REGISTRY: neuvector/neuvector-nexus-iq

    steps:
      - uses: actions/checkout@v2

      - name: Variables
        id: vars
        run: |
          BUILD_VERSION=$(git describe --tags --always)
          BUILD_COMMIT=$(git rev-parse HEAD)
          BUILD_TIME=$(date -u)
          echo "::set-env name=BUILD_VERSION::${BUILD_VERSION}"
          echo "::set-env name=BUILD_COMMIT::${BUILD_COMMIT}"
          echo "::set-env name=BUILD_TIME::${BUILD_TIME}"
          if [[ $BUILD_VERSION =~ ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$ ]]; then echo "::set-env name=RELEASE::true"; fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ env.RELEASE == 'true' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: ${{ env.RELEASE == 'true' }}
          tags: ${{ env.IMAGE_REGISTRY }}:${{ env.BUILD_VERSION }}
          build-args: |
            BUILD_VERSION=${{ env.BUILD_VERSION }}
            BUILD_COMMIT=${{ env.BUILD_COMMIT }}
            BUILD_TIME=${{ env.BUILD_TIME }}
